import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { createClient } from "@/libs/supabase/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Casho",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const getUser = async () => {
    const supabase = await createClient();
    const { data, error } = await supabase.auth.getUser();
    if (error) return console.log("col 30:", error);
    const { data: userData, error: errorUser } = await supabase.from("profiles").select().eq("user_id", data?.user?.id).single();
    console.log(userData)
    if (errorUser) {
      await supabase.from("profiles").insert({ user_id: data?.user?.id, username: data?.user?.user_metadata.full_name, profile_images: data?.user?.user_metadata?.avatar_url });
      return console.log("34", errorUser);
    }
    // console.log("layout 36",userData);
  }
  getUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
